### ISSUE TITLE
Error, could not get Blockonomics secret from database. Gateway Module "blockonomics" Not Activated

### ISSUE THREAD

**Issue by agarzon** [blockonomics/whmcs-bitcoin-plugin#104]
When  the plugin is deactivated from the WHMCS panel, the entire payment section in the admin panel gets blocked with this error:

`Error, could not get Blockonomics secret from database. Gateway Module "blockonomics" Not Activated`

In the code, actually there are several exit() functions that kills the entire process. Example:

https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/cdf4d963b42e6e32bba7f6e62a15aa6c2ab21c78/modules/gateways/blockonomics/blockonomics.php#L43
https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/cdf4d963b42e6e32bba7f6e62a15aa6c2ab21c78/modules/gateways/blockonomics/blockonomics.php#L52

The use of die() and exit() can be dangerous if missused.

**Comment by blockonomics** [comment]
@DarrenWestwood  Please see if this is a new issue in 1.9 or is existing in 1.8.2 also . Also feel free to add your thoughts

**Comment by DarrenWestwood** [comment]
This is a new issue after version 1.8.2, which is currently blocking installations of the module.
