### ISSUE TITLE
Invoice don't update to paid

### ISSUE THREAD

**Issue by mauwiks** [blockonomics/whmcs-bitcoin-plugin#115]
When a client pays, it doesn't update and I get this error 503 in the logs

**Comment by blockonomics** [comment]
Please consult the below article 
https://blockonomics.freshdesk.com/solution/articles/33000219539-order-status-not-changing-ddos-protection

**Comment by mauwiks** [comment]
I did this. Now it works not by that article instructions but by increasing the threshold of my DOS rate limit from 100 to 250 and yet the logs saying ReadTimeout https://bit.ly/353gAYl
