### ISSUE TITLE
Error: API Key is incorrect

### ISSUE THREAD

**Issue by zetas** [blockonomics/whmcs-bitcoin-plugin#123]
The last payment I received via blockonomics was at the beginning of may. This isn't all that unusual, bitcoin payments are few and far between but this morning one of my customers sent me a screenshot and notified me that the blockonimics payment gateway is broken:
![image](https://user-images.githubusercontent.com/1036810/121923217-b5e44300-cd08-11eb-9126-ad3ffd5a60a2.png)
When I click the test setup button I get `Error: API Key is incorrect`. I went to the merchants page and generated a new API Key, entered it in and saved the settings and when testing again I get the same error. I've repeated this 4 times with the same result. Does anyone have any ideas what could be wrong? I don't see any error messages.

**Comment by jusasiiv** [comment]
Hi, thank you for reaching out to us.

Can you tell me the plugin version you are using. You can find the version number from the Payment Gateway settings under  Blockonomics' settings. Some old versions of the plugin had a bug which caused the settings to not save the API key correctly.

**Comment by zetas** [comment]
Ok. Apparently I was using a version so old it didn't even have a version number. It just had 2 files in the Blockonomics directory: Blockonomics.php and Flyp.php. I went ahead and updated it to the latest version and it seems to be working now. Though I did have issues with it's database updates. It was complaining about lack of primary key on initial creation so I had to modify the schema to get it to be compatible with MySQL8, apparently when you use `$table->primary` after the column has been declared it tries to create the table first as-is and then runs a second query to add the primary key. That does not work with default MySQL8, the primary key must be included in the schema creation so I changed the "integer" of `id_order` to increments to make that the primary key, and added an `addr` unique index at the end to facilitate the same functionality as I assume was expected.

```php
Capsule::schema()->create(
                    'blockonomics_orders',
                    function ($table) {
                        $table->increments('id_order');
                        $table->text('txid');
                        $table->integer('timestamp');
                        $table->string('addr');
                        $table->integer('status');
                        $table->decimal('value', 10, 2);
                        $table->integer('bits');
                        $table->integer('bits_payed');
                        $table->string('blockonomics_currency');
                        $table->decimal('basecurrencyamount', 10, 2);
                        $table->unique('addr');
                    }
                );
```
Resulting in the following schema:
```
mysql> explain blockonomics_orders;
+-----------------------+---------------+------+-----+---------+----------------+
| Field                 | Type          | Null | Key | Default | Extra          |
+-----------------------+---------------+------+-----+---------+----------------+
| id_order              | int unsigned  | NO   | PRI | NULL    | auto_increment |
| txid                  | text          | NO   |     | NULL    |                |
| timestamp             | int           | NO   |     | NULL    |                |
| addr                  | varchar(255)  | NO   | UNI | NULL    |                |
| status                | int           | NO   |     | NULL    |                |
| value                 | decimal(10,2) | NO   |     | NULL    |                |
| bits                  | int           | NO   |     | NULL    |                |
| bits_payed            | int           | NO   |     | NULL    |                |
| blockonomics_currency | varchar(255)  | NO   |     | NULL    |                |
| basecurrencyamount    | decimal(10,2) | NO   |     | NULL    |                |
+-----------------------+---------------+------+-----+---------+----------------+
```

**Comment by blockonomics** [comment]
@zetas THanks a lot for reporting the issue and letting us know the fix also ! Tracking it [here ](https://github.com/blockonomics/whmcs-bitcoin-plugin/issues/124) and closing this
