### ISSUE TITLE
Misspelling in payment.tpl

### ISSUE THREAD

**Issue by bdrewery** [blockonomics/whmcs-bitcoin-plugin#15]
https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/b02fc93c2f9c6847aa498bd7cd0dad29ee360375/templates/blockonomics/payment.tpl#L58

"prefered" should be spelled "preferred"

**Comment by jusasiiv** [comment]
Fixed in https://github.com/blockonomics/whmcs-bitcoin-plugin/commit/d56f3c2712d5b8753e7b98aa9dfcea62c7f1a65e
