### ISSUE TITLE
Shapeshift region block fallback

### ISSUE THREAD

**Issue by bdrewery** [blockonomics/whmcs-bitcoin-plugin#16]
https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/b02fc93c2f9c6847aa498bd7cd0dad29ee360375/templates/blockonomics/payment.tpl#L59

Shapeshift is blocked in some regions (like even some states in the USA). Please consider some fallback here if the image cannot be loaded. I worked around it for now with an `alt` on the `img` tag:

```
alt="Altcoins via Shapeshift are not available in your region."
```

**Comment by jusasiiv** [comment]
Fixed in https://github.com/blockonomics/whmcs-bitcoin-plugin/commit/d56f3c2712d5b8753e7b98aa9dfcea62c7f1a65e
