### ISSUE TITLE
Test Setup is spinning and not executing

### ISSUE THREAD

**Issue by jusasiiv** [blockonomics/whmcs-bitcoin-plugin#20]
Example case of not being able to see payment page: File _payment.php_ is owned by _root:root_ and permission is set to _755_

Other files run fine and plugin setup is able to be completed but payment page wont display, it will give a 404 error.

**Comment by 15782aa9-553c-4b2a-8cc8-4fa15c680aae** [comment]
![arrowlist](https://user-images.githubusercontent.com/34982173/46286770-df1c0f80-c56f-11e8-8d8d-b0d9997c2f19.gif)

**Comment by blockonomics** [comment]
- Customer are reporting this in recent version. 
- It is confusing that other pages of plugin are showing and Test Setup is not working
- Show research a fix for this (maybe see other plugins ?)
