### ISSUE TITLE
Test Setup

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/whmcs-bitcoin-plugin#22]
- Added test setup features like wordpress / prestashop

**Comment by shivaenigma** [comment]
Added for code review:

- https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/071de530e33d8cabb39180ec0c53e1e578d69def/templates/blockonomics/payment.tpl#L366 has to be changed and made like woocommerce plugin. We tell admin to run testsetup to diagnose the issue
- https://github.com/blockonomics/whmcs-bitcoin-plugin/commit/071de530e33d8cabb39180ec0c53e1e578d69def#r32116753
