### ISSUE TITLE
Use curl instead of fopen_url

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/whmcs-bitcoin-plugin#23]
Whmcs already [requires curl](https://docs.whmcs.com/System_Requirements)

- Replace fopen calls with curl
- Refactor calls to go to a common function to avoid duplicate code

**Comment by jusasiiv** [comment]
Added in https://github.com/blockonomics/whmcs-bitcoin-plugin/commit/a0dd7e80757e4cab61e95a144a7bebec9612eb07
