### ISSUE TITLE
Using System URL may lead to losing POST params

### ISSUE THREAD

**Issue by jusasiiv** [blockonomics/whmcs-bitcoin-plugin#26]
In  _modules/gateways/blockonomics.php_ payment URL is formed with WHMCS System URL. If site has SSL activated but System URL points to HTTP version the `$_POST` parameters will be lost or 404 page is shown depending on redirection rules.

**Comment by blockonomics** [comment]
Investigate reasons of using system URL instead of relative URL

**Comment by jusasiiv** [comment]
Fixed with https://github.com/blockonomics/whmcs-bitcoin-plugin/commit/9ff0ceca981fa56f097d061c3bf34b81a05f8143
