### ISSUE TITLE
Temporary screen for low value payment

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/whmcs-bitcoin-plugin#29]
https://drive.google.com/file/d/1t0B_XTJo-1YgoW89IU6Df1aaWi1J2Tp1/view?usp=sharing

The payment itself when done is showing received screen which indicates the flyp me order was created

**Comment by jusasiiv** [comment]
Fixed with https://github.com/blockonomics/whmcs-bitcoin-plugin/commit/f465007ae5c1bfd3d115be38cfeb3376e1d7aad1
