### ISSUE TITLE
Custom theme needs manual copying of payment.tpl

### ISSUE THREAD

**Issue by jusasiiv** [blockonomics/whmcs-bitcoin-plugin#3]
Template is not loaded by using a path but by calling active template `$ca->setTemplate('payment');` 

WHMCS default theme is Six. If custom theme is used, the payment.tpl wont be loaded as it is located in templates/six/payment.tpl

Need to look if the template can be loaded/installed automatically on all templates.

**Comment by blockonomics** [comment]
Maybe `$ca->setTemplate('../six/payment');` could work. Just an idea !

**Comment by jusasiiv** [comment]
Creating a new folder `/templates/blockonomics/` an using `$ca->setTemplate('../blockonomics/payment');` seems to work at least with default theme. Need to be tested with custom theme also
