### ISSUE TITLE
Oops screen showing up

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/whmcs-bitcoin-plugin#31]
![datap pro error](https://user-images.githubusercontent.com/22165583/49498097-ff2dbf00-f88f-11e8-92bf-8f6f0fc44aba.png)

**Comment by jusasiiv** [comment]
Fixed with https://github.com/blockonomics/whmcs-bitcoin-plugin/commit/95d92652fd252c734a34b4feb753260ebc838281
