### ISSUE TITLE
Plugin giving fopen error uncessarily

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/whmcs-bitcoin-plugin#33]
- This [line](https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/4891ac0419703da422fe6eaf7ed5843985cd7e48/modules/gateways/Blockonomics/Blockonomics.php#L380) throws fopen error if not enabled
- It is not necessary as anyway we have switched to curl

Also related #22

**Comment by blockonomics** [comment]
Plugin should redirect user to use testsetup for error diagnosis
