### ISSUE TITLE
Prompt to save after setting API key

### ISSUE THREAD

**Issue by jusasiiv** [blockonomics/whmcs-bitcoin-plugin#35]
After user has set/changed their API key it is not clear that it needs to be saved by clicking Save. User might paste API key and run test setup which will give Incorrect API Key error.

Fix by detecting when API key has changed and prompt user to save the change.

**Comment by blockonomics** [comment]
- Paste API key 
- Then directly Click on Test Setup.

Should give error. Maybe better idea to detect this inside Test Setup rather than on _onchange_

**Comment by jusasiiv** [comment]
PR was merged
