### ISSUE TITLE
Mark invoice as paid without waiting for confirmations

### ISSUE THREAD

**Issue by yswery** [blockonomics/whmcs-bitcoin-plugin#49]
Can someone please confirm that if I edit the following:

https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/024f251e4a83643d39572f7f42a6ea5c25420706/modules/gateways/callback/blockonomics.php#L60-L62

and do the following:

```
if($status != 2 && $status != 1) {
	die();
}
```

it will result in the desired outcome of an invoice getting marked as accepted as soon as the BTC transaction is on the block-chain (but without confirmations)

Our object is to accept payments faster and not wait for any confirmations

**Comment by blockonomics** [comment]
Sometimes you directly get 1 or two confirmations. So above code will not work. Adding @DarrenWestwood  who can help you with the exact code

**Comment by DarrenWestwood** [comment]
https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/master/modules/gateways/callback/blockonomics.php#L111
`checkCbTransID($txid)` verifies the same transaction is not added to the invoice multiple times. We can therefore go ahead and remove 
```
if($status == 0) {
	$invoiceNote = "<b>Waiting for Confirmation on Bitcoin network</b>\r\r" .
		"Bitcoin transaction id:\r" .
		"<a target=\"_blank\" href=\"https://www.blockonomics.co/api/tx?txid=$txid&addr=$addr\">$txid</a>";
	$blockonomics->updateOrderInDb($addr, $txid, $status, $value);
	$true_order_id = $blockonomics->getOrderIdByInvoiceId($invoiceId);
	$blockonomics->updateInvoiceNote($invoiceId, $invoiceNote);
	die();
}
``` 
and change https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/master/modules/gateways/callback/blockonomics.php#L60-L62
```
if($status != 2) {
	die();
}
```
to
```
if($status != 2 && $status != 1 && $status != 0) {
	die();
}
```

**Comment by jusasiiv** [comment]
PR was merger
