### ISSUE TITLE
match_callback giving complete host URL

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/whmcs-bitcoin-plugin#52]
After the latest update, lots of hosts are submitting complete callbackURL in match_callback parameter

_200 POST /api/new_address?match_callback=https://zillionkinghost.com/billing/modules/gateways/cal
lback/blockonomics.php?secret=lkasjdlkasd1123_

This is uncessary

**Comment by jusasiiv** [comment]
PR merged
