### ISSUE TITLE
BTC as currency

### ISSUE THREAD

**Issue by DarrenWestwood** [blockonomics/whmcs-bitcoin-plugin#53]
- Incorrect total on checkout
- Underpayment is getting accepted
- No WHMCS currency format that allows more than two decimal places (0.01 BTC minimum and increments can be used for product prices)

**Comment by blockonomics** [comment]
Can you also summarize on how to set BTC as a currency in WHMCS. Is it straightforward like USD/EUR ?

**Comment by DarrenWestwood** [comment]
> Can you also summarize on how to set BTC as a currency in WHMCS. Is it straightforward like USD/EUR ?

Setup > Payments > Currencies
Click on _Edit Icon_ to edit the _Base Currency_
![WHMCS - Currencies](https://user-images.githubusercontent.com/39666372/66018218-777c0580-e4de-11e9-96ce-be837a5a7102.png)

Change the _Currency Code_ and _Suffix_ to **BTC**
Remove the _Prefix_
Check _Update Pricing_ and click _Save Changes_
![WHMCS - Currencies (1)](https://user-images.githubusercontent.com/39666372/66018506-a5ae1500-e4df-11e9-9e5e-a3f2ad015342.png)

**Comment by DarrenWestwood** [comment]
> * Incorrect total on checkout
> * Underpayment is getting accepted

Fixed with commit c49b466

> * No WHMCS currency format that allows more than two decimal places (0.01 BTC minimum and increments can be used for product prices)

Alter database tables to resolve issues with decimal places:
https://www.webhostingtalk.com/showthread.php?t=1327024
https://requests.whmcs.com/topic/number-of-possible-decimals-in-the-tax-rate-from-2-to-3

**Comment by blockonomics** [comment]
This requires a DB migration which break things(increases decimal) for normal users. The plan is 
1. Add a pull request that doesn't effect other users
2. Provide extra DB migration required which will be provided in FAQ and provided by our support when required

**Comment by DarrenWestwood** [comment]
The following command can be used for the DB migration:
```
SET sql_mode = '';
ALTER TABLE tblaccounts MODIFY amountin DECIMAL(10,8);
ALTER TABLE tblaccounts MODIFY fees DECIMAL(10,8);
ALTER TABLE tblaccounts MODIFY amountout DECIMAL(10,8);
ALTER TABLE tblaffiliates MODIFY payamount DECIMAL(10,8);
ALTER TABLE tblaffiliates MODIFY balance DECIMAL(10,8);
ALTER TABLE tblaffiliates MODIFY withdrawn DECIMAL(10,8);
ALTER TABLE tblaffiliateshistory MODIFY amount DECIMAL(10,8);
ALTER TABLE tblaffiliatespending MODIFY amount DECIMAL(10,8);
ALTER TABLE tblaffiliateswithdrawals MODIFY amount DECIMAL(10,8);
ALTER TABLE tblbillableitems MODIFY amount DECIMAL(10,8);
ALTER TABLE tblbundles MODIFY displayprice DECIMAL(10,8);
ALTER TABLE tblclients MODIFY credit DECIMAL(10,8);
ALTER TABLE tblcredit MODIFY amount DECIMAL(10,8);
ALTER TABLE tbldomainpricing MODIFY grace_period_fee DECIMAL(10,8);
ALTER TABLE tbldomainpricing MODIFY redemption_grace_period_fee DECIMAL(10,8);
ALTER TABLE tbldomainpricing_premium MODIFY to_amount DECIMAL(10,8);
ALTER TABLE tbldomains MODIFY firstpaymentamount DECIMAL(10,8);
ALTER TABLE tbldomains MODIFY recurringamount DECIMAL(10,8);
ALTER TABLE tblhosting MODIFY firstpaymentamount DECIMAL(10,8);
ALTER TABLE tblhosting MODIFY amount DECIMAL(10,8);
ALTER TABLE tblhostingaddons MODIFY setupfee DECIMAL(10,8);
ALTER TABLE tblhostingaddons MODIFY recurring DECIMAL(10,8);
ALTER TABLE tblinvoiceitems MODIFY amount DECIMAL(10,8);
ALTER TABLE tblinvoices MODIFY subtotal DECIMAL(10,8);
ALTER TABLE tblinvoices MODIFY  credit DECIMAL(10,8);
ALTER TABLE tblinvoices MODIFY tax DECIMAL(10,8);
ALTER TABLE tblinvoices MODIFY tax2 DECIMAL(10,8);
ALTER TABLE tblinvoices MODIFY total DECIMAL(10,8);
ALTER TABLE tblinvoices MODIFY taxrate DECIMAL(10,8);
ALTER TABLE tblinvoices MODIFY taxrate2 DECIMAL(10,8);
ALTER TABLE tblorders MODIFY amount DECIMAL(10,8);
ALTER TABLE tblpricing MODIFY msetupfee DECIMAL(10,8);
ALTER TABLE tblpricing MODIFY qsetupfee DECIMAL(10,8);
ALTER TABLE tblpricing MODIFY ssetupfee DECIMAL(10,8);
ALTER TABLE tblpricing MODIFY asetupfee DECIMAL(10,8);
ALTER TABLE tblpricing MODIFY bsetupfee DECIMAL(10,8);
ALTER TABLE tblpricing MODIFY tsetupfee DECIMAL(10,8);
ALTER TABLE tblpricing MODIFY monthly DECIMAL(10,8);
ALTER TABLE tblpricing MODIFY quarterly DECIMAL(10,8);
ALTER TABLE tblpricing MODIFY semiannually DECIMAL(10,8);
ALTER TABLE tblpricing MODIFY annually DECIMAL(10,8);
ALTER TABLE tblpricing MODIFY biennially DECIMAL(10,8);
ALTER TABLE tblpricing MODIFY triennially DECIMAL(10,8);
ALTER TABLE tblproducts MODIFY affiliatepayamount DECIMAL(10,8);
ALTER TABLE tblpromotions MODIFY value DECIMAL(10,8);
ALTER TABLE tblquoteitems MODIFY unitprice DECIMAL(10,8);
ALTER TABLE tblquoteitems MODIFY discount DECIMAL(10,8);
ALTER TABLE tblquotes MODIFY subtotal DECIMAL(10,8);
ALTER TABLE tblquotes MODIFY tax1 DECIMAL(10,8);
ALTER TABLE tblquotes MODIFY tax2 DECIMAL(10,8);
ALTER TABLE tblquotes MODIFY total DECIMAL(10,8);
ALTER TABLE tblservers MODIFY monthlycost DECIMAL(10,8);
ALTER TABLE tbltax MODIFY taxrate DECIMAL(10,8);
ALTER TABLE tblupgrades MODIFY amount DECIMAL(10,8);
ALTER TABLE tblupgrades MODIFY credit_amount DECIMAL(10,8);
ALTER TABLE tblupgrades MODIFY new_recurring_amount DECIMAL(10,8);
ALTER TABLE tblupgrades MODIFY recurringchange DECIMAL(10,8);
```
This allows product prices to be correctly set to 8 decimals in WHMCS admin.

We are still required to edit our frontend to not format prices to 2 decimals. This can be achieved by editing the current template files or creating our own. The changes are complex for each individual user.

**Comment by blockonomics** [comment]
Ok please resolve the conflicts in pull request. More progress on this issue can be deferred for now

**Comment by blockonomics** [comment]
Closing in favour of https://github.com/blockonomics/whmcs-bitcoin-plugin/issues/63
