### ISSUE TITLE
Click here to go back on Altcoin Page

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/whmcs-bitcoin-plugin#58]
- Goes back to payment.php which is POST request
- Firefox give a warning and if users says try again, then it works

Let us list possible solutions first

**Comment by DarrenWestwood** [comment]
We can resolve by changing to GET request here:
https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/master/modules/gateways/blockonomics.php#L203
and here:
https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/master/payment.php#L31-L33

**Comment by blockonomics** [comment]
> We can resolve by changing to GET request here:
> https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/master/modules/gateways/blockonomics.php#L203
> and here:
> https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/master/payment.php#L31-L33

Posting params to GET request isn't very secure and doesn't feel right. Let us just remove Click here to go back message for now

WHMCS has very good way to pay unpaid invoices and users are not using press back on payment page anyway
