### ISSUE TITLE
Blockonomics not displayed under Manage Existing Gateways

### ISSUE THREAD

**Issue by DarrenWestwood** [blockonomics/whmcs-bitcoin-plugin#60]
CallbackSecret is getting generated before the plugin is activated.
This leads to an error where the gateway is shown active from 'All Payment Gateways' but does not show under 'Manage Existing Gateways'.

Reproduce:
- Copy Blockonomics files or deactivate Blockonomics gateway
- Visit 'All Payment Gateways'
- Refresh the page

Temp fix:
From 'tblpaymentgateways' database table delete the row with setting = 'CallbackSecret'

**Comment by blockonomics** [comment]
Lets move to this a separate pull request, so that it can be resolved

**Comment by blockonomics** [comment]
Taggging this to high priority

**Comment by DarrenWestwood** [comment]
Pull request: https://github.com/blockonomics/whmcs-bitcoin-plugin/pull/61

**Comment by jusasiiv** [comment]
Fixed by PR
