### ISSUE TITLE
UI Update - Send exact amount

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/whmcs-bitcoin-plugin#7]
Users are getting confused on what BTC amount to send. To avoid the message
_To pay send 0.0011 BTC to 1Aasjd..._ is better.

- [Example ](https://screenshots.firefox.com/WbEcW4K9CVj67c6t/coingate.com), also our payment button this is very clear
- Rearrange UI elements to add this message and remove the existing one

We want this UI in other plugins as well later

**Comment by shivaenigma** [comment]
![layout_mockup_3](https://user-images.githubusercontent.com/737092/36840322-8ddfd6a4-1d6a-11e8-88e5-26d059925e64.png)

Talking with designer for UI review. Don't implement yet

**Comment by blockonomics** [comment]
Closing a duplicate of #8
