### ISSUE TITLE
Multiple payments on one transaction

### ISSUE THREAD

**Issue by jusasiiv** [blockonomics/whmcs-bitcoin-plugin#79]
In the rare case that a customer pays several invoices with one transaction, only one invoice is marked paid. This is caused by identifying if a transaction has been applied by only looking at the txid https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/master/modules/gateways/Blockonomics/Blockonomics.php#L195

To fix, check both txid and address when applying payment to invoice.

**Comment by DarrenWestwood** [comment]
Reported by another user.

**Comment by blockonomics** [comment]
Currently `$txid = 'WarningThisIsATestTransaction_' . $addr;`  works for test transaction. Same can be done for all payments. Let us think about implications of this

**Comment by Al-Bsharat** [comment]
Hello,
When will you update the module on the WHMCS Marketplace?
