### ISSUE TITLE
Convert to for processing setting

### ISSUE THREAD

**Issue by DarrenWestwood** [blockonomics/whmcs-bitcoin-plugin#80]
Using the Convert to for processing setting converts the currency amount on the final invoice incorrectly. 

500TIR is converted to 30USD on checkout. 
The invoice is marked as receiving 30TIR instead of 500TIR or 30USD

**Comment by shivaenigma** [comment]
Can you attach screenshot for more clarity

**Comment by DarrenWestwood** [comment]
Convert to for processing set to **GBP** (conversion set at 2:1)
![WHMCS_Payment_Gateways](https://user-images.githubusercontent.com/39666372/87000734-09bfe100-c1b6-11ea-9f64-017553d590fe.png)

The order total is $25
![Shopping_Cart_Company_Name (1)](https://user-images.githubusercontent.com/39666372/87000599-c5ccdc00-c1b5-11ea-8a93-5ffbe8da0d0f.png)

This is correctly converted to GBP in the checkout
![Bitcoin_Payment_Company_Name](https://user-images.githubusercontent.com/39666372/87000608-c8c7cc80-c1b5-11ea-8962-9d1b8c4ff646.png)

After confirmation, the amount in the invoice should be **25 USD** not 50 USD. Callbacks are using the converted value and not the original invoice value
![Company_Name_Invoice_2](https://user-images.githubusercontent.com/39666372/87000613-cb2a2680-c1b5-11ea-9412-43839227a3ac.png)

**Comment by DarrenWestwood** [comment]
This appears to be an issue with WHMCS and present with other payment gateways as well. 
A feature request to fix this behaviour has been been opened with WHMCS, however this feature is still under consideration:
https://requests.whmcs.com/topic/convert-to-for-processing-credit-card-gateways-callback#comment-9888
Please vote by clicking on the "I like this idea" button.

**Comment by DarrenWestwood** [comment]
### Solution

- The currency should be saved with the blockonomics order in the database. Existing users should be able to upgrade without issue.

- In the Blockonomics callback, before the payment is added to the invoice, check the expected_invoice_currency for the invoice. This can be achieved using `GetClientsDetails`:
    https://developers.whmcs.com/api-reference/getclientsdetails/

    An example of a previous usage can be found here: 
    https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/fec4eda13aad13fe59555b070767446847f1cb79/modules/gateways/Blockonomics/Blockonomics.php#L545-L561
    To double check the expected currency is correct, also check if the Convert to for processing setting matches that returned from `GetClientsDetails`

- The expected_invoice_currency should be compared to the currency saved with the blockonomics order in the first step.

- If the invoice currency differs from the blockonomics order currency, the $paymentAmount should be converted to the correct invoice currency before `addInvoicePayment`:
    https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/09f5ef536f16c109e1c5527f16338230cc6dda4f/modules/gateways/callback/blockonomics.php#L144-L150

    To handle the conversion, the conversion rates can be found using `GetCurrencies`:
    https://developers.whmcs.com/api-reference/getcurrencies/

**Comment by shivaenigma** [comment]
Asked by another customer

**Comment by DarrenWestwood** [comment]
GetClientsDetails() is a client-side function and cannot be used unless the user is logged in. This means it is not viable for use within the callback code.

PR https://github.com/blockonomics/whmcs-bitcoin-plugin/pull/93 is working for conversions from the _convertto_currency_ to the _base_currency_ but does not work if a new user selects a currency during checkout that is not the _base_currency_.
![Shopping-Cart-Company-Name](https://user-images.githubusercontent.com/39666372/96725066-cb3ee280-13b0-11eb-9112-3f7935e331b4.png)

### Updated Fix
- Save the conversion rate during the checkout
- Retrieve the conversion rate during callbacks to calculate the order amount

**Comment by agarzon** [comment]
@DarrenWestwood Hi, I'm gonna put my hands into this issue, anyway to schedule a chat or videocall tomorrow or so? let me know (by slack)

**Comment by agarzon** [comment]
> GetClientsDetails() is a client-side function and cannot be used unless the user is logged in. This means it is not viable for use within the callback code.

Hi, in WHMCS the user cannot change the currency in the frontend once you are loggedin. You can see the prices in different currencies when you are not loggedin, once you create the account a default currency is attached to your profile (forever), yes one of multiples cons and unexplainable errors from WHMCS. That way all the user invoices will always be in a defined currency. Multicurrencies for the same user is not supported (yet)

**Comment by agarzon** [comment]
I just learned that if you do not use the converter we can safe all this problems. The invoices are proccesed correctly in the right currency.

Just tested with different users that uses different curencies: COP, VEF, CAD etc...

![image](https://user-images.githubusercontent.com/339828/99162719-bbc06a00-26ce-11eb-926b-821f9276a9e4.png)

So basically if we enforce users in the installation steps to leave `Convert To For Processing` in `none` we could avoid correcting this by code.

**Comment by DarrenWestwood** [comment]
Hi @agarzon, I have sent you a slack, let's chat there. This setting is required for currencies supported by WHMCS but not by Blockonomics. There have been some clients using this setting who reported the incorrect behaviour with the setting.
