### ISSUE TITLE
Php files in root directory

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/whmcs-bitcoin-plugin#83]
*payment.php* and *testsetup.php* in root directory are creating issue
- Polluting namespace
- Creating permission issues

Please move to internal directory. For example see https://github.com/bitpay/whmcs-plugin and https://github.com/WHMCS/sample-gateway-module

**Comment by agarzon** [comment]
@shivaenigma this has been fixed with https://github.com/blockonomics/whmcs-bitcoin-plugin/pull/92
