### ISSUE TITLE
WHMCS 8 breaks the plugin

### ISSUE THREAD

**Issue by jusasiiv** [blockonomics/whmcs-bitcoin-plugin#84]
WHMCS version 8 hashes/encodes plugin setting values. Our plugin fetches its setting values straight from the DB using constructed queries ([see example](https://github.com/blockonomics/whmcs-bitcoin-plugin/blob/master/modules/gateways/Blockonomics/Blockonomics.php#L90)) so returned value is not the actual value but the hashed string

Options for fix:
1. Find out the hashing/encoding and reverse it before returning the value
2. Use the $params array to fetch for the values, [see doc](https://developers.whmcs.com/payment-gateways/configuration/)

**Comment by sam43434** [comment]
+1
