### ISSUE TITLE
Why this plugin does not follow the WHMCS convention?

### ISSUE THREAD

**Issue by agarzon** [blockonomics/whmcs-bitcoin-plugin#91]
Hi.

I've been coding for WHMCS for a while and been creating hooks, addons, modules functions  and others hacks all based in the WHMCS dev documentation.

I use this plugin, but I cannot stop thinking why this was made in such way that all files and folder are placed in very bad places, it does not even follow any code convention. No files or folder should be ever created in the root folder, even the one inside the templates folder is in the wrong place.

Everything can be packed and route propertly inside the gateways folder, all assets, css, js images, templates, test script, etc...

I could refactor the code to make it follow the WHMCS conventions, but I'm afraid it could be a waste of time seeing how other pull requests has been ignored or been pending for months.

The plugin works, yes but the code is just not appropiate.

**Comment by shivaenigma** [comment]
Hi @agarzon  Thanks  for logging.  Yes we are partially [aware of this](https://github.com/blockonomics/whmcs-bitcoin-plugin/issues/83). However, we haven't been able to get around taking this up and our developers aren't so well aware of WHMCS conventions

Feel free to create a pull request and we would be happy to merge it in

**Comment by shivaenigma** [comment]
Would also be happy to assist your efforts monetarily. Feel free to reach out to me on webmaster at blockonomics.co

**Comment by agarzon** [comment]
And I would accept credits in my blockonomics account 😂

I will fork this latest version 1.8.0 and will start from there, my goal is to refactor the file locations and keeping untouched the logic. A PSR2 clean will be applied also and maybe having a bit of unit test will come handy.

**Comment by shivaenigma** [comment]
Awesome , please fork from currently master as we recently merged in [translation structure](https://github.com/blockonomics/whmcs-bitcoin-plugin/pull/90)

**Comment by agarzon** [comment]
The PR has been pushed https://github.com/blockonomics/whmcs-bitcoin-plugin/pull/92 but looks like they were some changes since I forked.

**Comment by agarzon** [comment]
Is fixed, I just rebased

**Comment by shivaenigma** [comment]
Hi @agarzon do you have sometime to chat on our slack channel. Would be great. Here is [the invite](https://join.slack.com/t/blockonomics/shared_invite/zt-i0yayrhg-zgzQCyrQ2qewMEYABERDYA)

**Comment by agarzon** [comment]
Merged, so closing this issue. Thanks for accepting this change.
