### ISSUE TITLE
WHMCS 8 breaks templating and "Could not generate new Bitcoin address"

### ISSUE THREAD

**Issue by yswery** [blockonomics/whmcs-bitcoin-plugin#96]
When trying to make a paymnet via blockonomics I get the following error in screenshot:

<img width="685" alt="Screen Shot 2020-10-26 at 11 08 13 PM" src="https://user-images.githubusercontent.com/6571918/97159800-41dc4580-17e0-11eb-9f92-18a1d20f36db.png">

**I am running: WHMCS 8.0.3 and blockonomics 1.8.2**

When I am in payment gateway I get a success test:
<img width="777" alt="Screen Shot 2020-10-26 at 11 11 48 PM" src="https://user-images.githubusercontent.com/6571918/97160075-b1eacb80-17e0-11eb-936a-f4fc410f7307.png">

**Comment by DarrenWestwood** [comment]
Hi @yswery 

There is a new version of the Blockonomics module, the new version adds support for WHMCS 8 and you can get it from GitHub and the WHMCS marketplace.

After you have updated the module, remember that you have to clear your browser's cache as the files have changed. This ensures that you get all of the new files and not old ones from the cache. You can also use private/incognito mode to force a clear cache.
https://www.pcmag.com/how-to/how-to-clear-your-cache-on-any-browser

If you face any issues with the new release please let us know and we will work with you to fix any problems.

**Comment by yswery** [comment]
Closing issue, this was a caching thing as you mentioned.

Thanks for your time
